In [12]:
# Install NumPy and check the version

%pip install numpy
import numpy as np
print(np.__version__)

### Part 1: NumPy Array Manipulation (The Core Data) ###________________________

### 1. Create Product Data 

np.random.seed(0)  # seed for reproducibility

product_ids = np.arange(1000,1010) # 1-dimensional array
product_ids

# Creation of columns before using the stack command

stock = np.random.randint(10, 120, size = 10, dtype = 'int64')
avg_w_sales = np.random.uniform(3.2, 25.0, size = 10)
avg_w_sales = np.round(avg_w_sales, 2) # rounding the floats to 2 decimal places
unit_cost = np.random.uniform(5.00, 50.50, size = 10)
unit_cost = np.round(unit_cost, 2) # rounding the floats to 2 decimal places
print(stock, avg_w_sales, unit_cost)

# Stacking the columns into a 10,3 array

inventory_data = np.column_stack((stock, avg_w_sales, unit_cost))
inventory_data



Note: you may need to restart the kernel to use updated packages.
2.3.5
[ 54  57  74  77  77 113  19  93  31  46] [ 9.69  4.44  9.14 13.61 20.91 13.66 11.76 21.43 10.56 17.33] [21.75 48.55 11.39 44.59 26.55 41.44 28.68 35.89 37.79 31.48]


array([[ 54.  ,   9.69,  21.75],
       [ 57.  ,   4.44,  48.55],
       [ 74.  ,   9.14,  11.39],
       [ 77.  ,  13.61,  44.59],
       [ 77.  ,  20.91,  26.55],
       [113.  ,  13.66,  41.44],
       [ 19.  ,  11.76,  28.68],
       [ 93.  ,  21.43,  35.89],
       [ 31.  ,  10.56,  37.79],
       [ 46.  ,  17.33,  31.48]])

I wasn't sure about the correct method for creating a 10, 3 array with different data types so I created 3 seperate columns and stack them into a single array.

In [ ]:

###  2. Basic calculations and attributes

print("Inventory shape: ", inventory_data.shape) # Shape of the inventory data array
print("Inventory data type: ", inventory_data.dtype) # Data type of the inventory data array

total_value = stock * unit_cost # Total value of the current stock for all products
print(total_value)


Inventory shape:  (10, 3)
Inventory data type:  float64
[1174.5  2767.35  842.86 3433.43 2044.35 4682.72  544.92 3337.77 1171.49
 1448.08]
Products from 3 to 7:  [[ 77.    13.61  44.59]
 [ 77.    20.91  26.55]
 [113.    13.66  41.44]
 [ 19.    11.76  28.68]
 [ 93.    21.43  35.89]]
Average weekly sales (mean):  13.25
Unit cost of the first product:  21.75


In [ ]:
# 3. Slicing, Indexing, and Statistics:

product_3_7 = inventory_data[3:8]# Extract the data from product 3 to 7 (inclusive)
print("Products from 3 to 7: ", product_3_7)

avg_w_sales_mean = np.mean(avg_w_sales) # Extract the average of the Average Weekly Sales across all 10 products
avg_w_sales_mean = np.round(avg_w_sales_mean, 2)
print("Average weekly sales (mean): ", avg_w_sales_mean)

unit_cost_1st_product = inventory_data[0,2] # Unit cost of the 1st product
print("Unit cost of the first product: ", unit_cost_1st_product)



In [14]:

### Part 2: Advanced NumPy Analysis (Re-stocking Logic) ###______________________

### 1. Boolean Masking (The "Low-Stock" Check):

weeks_of_stock = stock / avg_w_sales # Calculate the number of weeks the current stock will last based on average sales.
weeks_of_stock = np.round(weeks_of_stock, 2)
print("Remaining weeks of stock: ", weeks_of_stock)

low_stock = (weeks_of_stock < 4) # Create a boolean mask that is True for any product where the Weeks of Stock is less than 4 (i.e., less than a month's supply).
low_stock_products = inventory_data[low_stock] # Extract and print the entire rows from inventory_data for the products that are low in stock.
print("Low stock products: ", low_stock_products)


Remaining weeks of stock:  [ 5.57 12.84  8.1   5.66  3.68  8.27  1.62  4.34  2.94  2.65]
Low stock products:  [[77.   20.91 26.55]
 [19.   11.76 28.68]
 [31.   10.56 37.79]
 [46.   17.33 31.48]]


In [15]:

### 2. Reshaping and Concatenation (Updating Data):

reorder_quantity = np.array((4 * avg_w_sales) - stock) # Create a new 1-dimensional NumPy array named reorder_quantity where each value is calculated as: (4 * Average Weekly Sales) - Current Stock Level (i.e., enough to bring stock up to a 4-week supply).
reorder_quantity = np.abs(reorder_quantity) # Return absolute values
print(reorder_quantity)

reorder_quantity_2D = reorder_quantity.reshape(10, 1) # Reshape the reorder_quantity array to a (10, 1) 2D array.
print(reorder_quantity_2D)

new_inventory_data = np.concatenate ((inventory_data,reorder_quantity_2D), axis=1)
print("New reordered inventory: ", new_inventory_data) # Combine the original inventory_data array with the new reorder_quantity array along the appropriate axis (resulting in a (10, 4) array).


[15.24 39.24 37.44 22.56  6.64 58.36 28.04  7.28 11.24 23.32]
[[15.24]
 [39.24]
 [37.44]
 [22.56]
 [ 6.64]
 [58.36]
 [28.04]
 [ 7.28]
 [11.24]
 [23.32]]
New reordered inventory:  [[ 54.     9.69  21.75  15.24]
 [ 57.     4.44  48.55  39.24]
 [ 74.     9.14  11.39  37.44]
 [ 77.    13.61  44.59  22.56]
 [ 77.    20.91  26.55   6.64]
 [113.    13.66  41.44  58.36]
 [ 19.    11.76  28.68  28.04]
 [ 93.    21.43  35.89   7.28]
 [ 31.    10.56  37.79  11.24]
 [ 46.    17.33  31.48  23.32]]


In [16]:
### Part 3: Introduction to Pandas (Viewing the Results) ###_________________

%pip install pandas
import pandas as pd

### 1. Create a DataFrame:

df_inventory = pd.DataFrame(new_inventory_data, columns = ['Stock', 'Sales', 'Cost', 'Reorder Qty']) # Create a Pandas DataFrame and assign the appropriate columns name


Note: you may need to restart the kernel to use updated packages.


In [17]:
### 2. Basic Selection:
 
print(df_inventory[['Stock', "Reorder Qty"]]) # Print only Stock and Reorder Qty columns

print(df_inventory.head(5)) # Print the first 5 rows of the DataFrame.

   Stock  Reorder Qty
0   54.0        15.24
1   57.0        39.24
2   74.0        37.44
3   77.0        22.56
4   77.0         6.64
5  113.0        58.36
6   19.0        28.04
7   93.0         7.28
8   31.0        11.24
9   46.0        23.32
   Stock  Sales   Cost  Reorder Qty
0   54.0   9.69  21.75        15.24
1   57.0   4.44  48.55        39.24
2   74.0   9.14  11.39        37.44
3   77.0  13.61  44.59        22.56
4   77.0  20.91  26.55         6.64
